export const DEGUSTATOR_PRESS_BTN = "DEGUSTATOR_PRESS_BTN";
export const DEGUSTATOR_SUM = "DEGUSTATOR_SUM";
export const WINE_ELIMINATE = "WINE_ELIMINATE";
export const WINE_ID = "WINE_ID";
export const DEGUSTATOR_COMMENT = "DEGUSTATOR_COMMENT";

export const FETCH_WINE_IN_GROUP_START = "FETCH_WINE_IN_GROUP_START";
export const FETCH_WINE_IN_GROUP_SUCCESS = "FETCH_WINE_IN_GROUP_SUCCESS";
export const FETCH_WINE_IN_GROUP_FAIL = "FETCH_WINE_IN_GROUP_FAIL";

export const FETCH_WINE_INFO_START = "FETCH_WINE_INFO_START";
export const FETCH_WINE_INFO_SUCCES = "FETCH_WINE_INFO_SUCCES";
export const FETCH_WINE_INFO_FAIL = "FETCH_WINE_INFO_FAIL";
export const RESULT_CLEAR_ERROR = "RESULT_CLEAR_ERROR";
export const CLEAR_RESULTS_SEND_MESSAGE = "CLEAR_RESULTS_SEND_MESSAGE";

export const RESULTS_SEND_INIT = "RESULTS_SEND_INIT";
export const RESULTS_SEND_START = "RESULTS_SEND_START";
export const RESULTS_SEND_FAIL = "RESULTS_SEND_FAIL";
export const RESULTS_SEND_SUCCESS = "RESULTS_SEND_SUCCESS";
export const RESULTS_SEND_CANCELED = "RESULTS_SEN_CANCELED";
export const RESET_RESULTS = "RESET_RESULTS";

export const FETCH_DEG_RESULTS_START = "FETCH_DEG_RESULTS_START";
export const FETCH_DEG_RESULTS_FAIL = "FETCH_DEG_RESULTS_FAIL";
export const FETCH_DEG_RESULTS_SUCCES = "FETCH_DEG_RESULTS_SUCCES";

export const FETCH_DEG_RESULT_BY_ID_START = "FETCH_DEG_RESULT_BY_ID_START";
export const FETCH_DEG_RESULT_BY_ID_SUCCES = "FETCH_DEG_RESULT_BY_ID_SUCCES";
export const FETCH_DEG_RESULT_BY_ID_FAIL = "FETCH_DEG_RESULT_BY_ID_FAIL";

export const CLOSE_DETAIL_RESULT = "CLOSE_DETAIL_RESULT";
export const DEG_RESULTS_CLEAR_ERROR = "DEG_RESULTS_CLEAR_ERROR";

export const LOGIN_START = "LOGIN_START";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";
export const LOGIN_CLEAR_ERROR = "LOGIN_CLEAR_ERROR";
export const SET_DID_TRY_AL = "SET_DID_TRY_AL";

export const SET_BASE_URL = "SET_BASE_URL";
export const GET_BASE_URL = "GET_BASE_URL";
export const RESET_BASE_URL = "RESET_BASE_URL";
