export const DEGUSTATOR_PRESS_BTN = "DEGUSTATOR_PRESS_BTN";
export const DEGUSTATOR_SUM = "DEGUSTATOR_SUM";
export const WINE_ELIMINATE = "WINE_ELIMINATE";
export const WINE_ID = "WINE_ID";
export const DEGUSTATOR_COMMENT = "DEGUSTATOR_COMMENT";

export const FETCH_WINE_INFO_START = "FETCH_WINE_INFO_START";
export const FETCH_WINE_INFO_SUCCES = "FETCH_WINE_INFO_SUCCES";
export const FETCH_WINE_INFO_FAIL = "FETCH_WINE_INFO_FAIL";