export const DEGUSTATOR_PRESS_BTN = "DEGUSTATOR_PRESS_BTN";
export const DEGUSTATOR_SUM = "DEGUSTATOR_SUM";
export const WINE_ELIMINATE = "WINE_ELIMINATE";
export const WINE_ID = "WINE_ID";
export const DEGUSTATOR_COMMENT = "DEGUSTATOR_COMMENT";

export const FETCH_WINE_IN_GROUP_START = "FETCH_WINE_IN_GROUP_START";
export const FETCH_WINE_IN_GROUP_SUCCESS = "FETCH_WINE_IN_GROUP_SUCCESS";
export const FETCH_WINE_IN_GROUP_FAIL = "FETCH_WINE_IN_GROUP_FAIL";

export const FETCH_WINE_INFO_START = "FETCH_WINE_INFO_START";
export const FETCH_WINE_INFO_SUCCES = "FETCH_WINE_INFO_SUCCES";
export const FETCH_WINE_INFO_FAIL = "FETCH_WINE_INFO_FAIL";
export const RESULT_CLEAR_ERROR = "RESULT_CLEAR_ERROR";
export const CLEAR_RESULTS_SEND_MESSAGE = "CLEAR_RESULTS_SEND_MESSAGE";

export const RESULTS_SEND_INIT = "RESULTS_SEND_INIT";
export const RESULTS_SEND_START = "RESULTS_SEND_START";
export const RESULTS_SEND_FAIL = "RESULTS_SEND_FAIL";
export const RESULTS_SEND_SUCCESS = "RESULTS_SEND_SUCCESS";
export const RESULTS_SEND_CANCELED = "RESULTS_SEN_CANCELED";
